/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Safe to run",
  "tagline": "Secure your mobile apps",
  "url": "https://safetorun.github.io/safe_to_run",
  "baseUrl": "/safe_to_run/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "safetorun",
  "projectName": "safe_to_run",
  "plugins": [
    "docusaurus-node-polyfills"
  ],
  "themeConfig": {
    "twitter": true,
    "twitterUsername": "safe_run",
    "twitterImage": "https://pbs.twimg.com/profile_images/1408694411215638530/81oDI0da_400x400.jpg",
    "navbar": {
      "title": "Safe to run",
      "logo": {
        "alt": "Safe to run",
        "src": "img/safetorun.jpg"
      },
      "items": [
        {
          "to": "docs/",
          "activeBasePath": "docs",
          "label": "Docs",
          "position": "left"
        },
        {
          "href": "https://github.com/safetorun/safe_to_run/",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [],
      "copyright": "Copyright © 2022 Safe to run. Built with Docusaurus."
    },
    "prism": {
      "additionalLanguages": [
        "kotlin",
        "groovy"
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadata": [],
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/Users/dllewellyn/Developer/safe_to_run_docs/safetorun.github.io/sidebars.js",
          "editUrl": "https://github.com/safetorun/safe_to_run_docs/edit/master/"
        },
        "googleAnalytics": {
          "trackingID": "UA-158023887-2",
          "anonymizeIP": true
        },
        "gtag": {
          "trackingID": "UA-158023887-2",
          "anonymizeIP": true
        }
      }
    ],
    [
      "@docusaurus/plugin-sitemap",
      {
        "changefreq": "weekly",
        "priority": 0.5,
        "trailingSlash": false
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
