name: React app deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: NPM-Version
      uses: Reedyuk/NPM-Version@1.1.1
      with:
        version: 7.10.0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install && npm run build
    - name: Deploy react app to github pages
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        path: build
