name: React app deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: NPM-Version
      uses: Reedyuk/NPM-Version@1.1.1
      with:
        version: 7.10.0
    - name: Deploy react app to github pages
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
